import Head from 'next/head'
import '@/styles/globals.css'
import { Header } from '@/coponents/Header';
import { useBgColor } from '@/hooks/useBgColor';


export const App = ({ Component, pageProps }) => {
  useBgColor();

  return(
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      
      <Component {...pageProps} />
    </>
  ) 
}

export default App;